osx_instance:
  image: mojave-xcode-10.2

task:
  script: |
    git submodule update --init --force
    make -C Dependencies/Libmacgpg
    make
    mkdir -p artifacts
  libmacgpg_artifacts:
    path: Dependencies/Libmacgpg/build/Release/Libmacgpg.framework
  gpgmail_artifacts:
    path: build/Release/GPGMail.mailbundle
