name="GPGMail"
appNamme="GPGMail.mailbundle"

pkgProj_dir="Installer"
pkgProj_corename="GPGMail_Core.pkgproj"
pkgCoreName="GPGMail_Core.pkg"
pkgProj_name="GPGMail.pkgproj"
pkgName="GPGMail.pkg"

rmName="Uninstall.app"

dmgName="GPGMail-1.4.1.dmg"
imgBackground="Installer/background_dmg.png"
volumeLayout="Installer/DS_Store"

sshKeyname="Sparkle GPGMail - Private key"

html="gpgmail"
dmgUrl="GPGTools/GPGMail"
downloadUrlPrefix="https://github.com/downloads/GPGMail/GPGMail/"



unset REVISION PRERELEASE


MAJOR=1
MINOR=4
REVISION=1
#PRERELEASE=b8



source "$(dirname "${BASH_SOURCE[0]}")/Dependencies/GPGTools_Core/newBuildSystem/versioning.sh"
